/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedStudentAttendanceRouteImport } from './routes/_authenticated/student-attendance'
import { Route as AuthenticatedStudentDashboardRouteImport } from './routes/_authenticated/student-dashboard'
import { Route as AuthenticatedStudentNoticesRouteImport } from './routes/_authenticated/student-notices'
import { Route as AuthenticatedTeacherAttendanceRouteImport } from './routes/_authenticated/teacher-attendance'
import { Route as AuthenticatedTeacherDashboardRouteImport } from './routes/_authenticated/teacher-dashboard'
import { Route as AuthenticatedTeacherNoticesRouteImport } from './routes/_authenticated/teacher-notices'
import { Route as AuthenticatedTeacherSubjectsRouteImport } from './routes/_authenticated/teacher-subjects'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStudentAttendanceRoute =
  AuthenticatedStudentAttendanceRouteImport.update({
    id: '/student-attendance',
    path: '/student-attendance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentDashboardRoute =
  AuthenticatedStudentDashboardRouteImport.update({
    id: '/student-dashboard',
    path: '/student-dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentNoticesRoute =
  AuthenticatedStudentNoticesRouteImport.update({
    id: '/student-notices',
    path: '/student-notices',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeacherAttendanceRoute =
  AuthenticatedTeacherAttendanceRouteImport.update({
    id: '/teacher-attendance',
    path: '/teacher-attendance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeacherDashboardRoute =
  AuthenticatedTeacherDashboardRouteImport.update({
    id: '/teacher-dashboard',
    path: '/teacher-dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeacherNoticesRoute =
  AuthenticatedTeacherNoticesRouteImport.update({
    id: '/teacher-notices',
    path: '/teacher-notices',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeacherSubjectsRoute =
  AuthenticatedTeacherSubjectsRouteImport.update({
    id: '/teacher-subjects',
    path: '/teacher-subjects',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/student-attendance': typeof AuthenticatedStudentAttendanceRoute
  '/student-dashboard': typeof AuthenticatedStudentDashboardRoute
  '/student-notices': typeof AuthenticatedStudentNoticesRoute
  '/teacher-attendance': typeof AuthenticatedTeacherAttendanceRoute
  '/teacher-dashboard': typeof AuthenticatedTeacherDashboardRoute
  '/teacher-notices': typeof AuthenticatedTeacherNoticesRoute
  '/teacher-subjects': typeof AuthenticatedTeacherSubjectsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/student-attendance': typeof AuthenticatedStudentAttendanceRoute
  '/student-dashboard': typeof AuthenticatedStudentDashboardRoute
  '/student-notices': typeof AuthenticatedStudentNoticesRoute
  '/teacher-attendance': typeof AuthenticatedTeacherAttendanceRoute
  '/teacher-dashboard': typeof AuthenticatedTeacherDashboardRoute
  '/teacher-notices': typeof AuthenticatedTeacherNoticesRoute
  '/teacher-subjects': typeof AuthenticatedTeacherSubjectsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/student-attendance': typeof AuthenticatedStudentAttendanceRoute
  '/_authenticated/student-dashboard': typeof AuthenticatedStudentDashboardRoute
  '/_authenticated/student-notices': typeof AuthenticatedStudentNoticesRoute
  '/_authenticated/teacher-attendance': typeof AuthenticatedTeacherAttendanceRoute
  '/_authenticated/teacher-dashboard': typeof AuthenticatedTeacherDashboardRoute
  '/_authenticated/teacher-notices': typeof AuthenticatedTeacherNoticesRoute
  '/_authenticated/teacher-subjects': typeof AuthenticatedTeacherSubjectsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/student-attendance'
    | '/student-dashboard'
    | '/student-notices'
    | '/teacher-attendance'
    | '/teacher-dashboard'
    | '/teacher-notices'
    | '/teacher-subjects'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/student-attendance'
    | '/student-dashboard'
    | '/student-notices'
    | '/teacher-attendance'
    | '/teacher-dashboard'
    | '/teacher-notices'
    | '/teacher-subjects'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/student-attendance'
    | '/_authenticated/student-dashboard'
    | '/_authenticated/student-notices'
    | '/_authenticated/teacher-attendance'
    | '/_authenticated/teacher-dashboard'
    | '/_authenticated/teacher-notices'
    | '/_authenticated/teacher-subjects'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/student-attendance': {
      id: '/_authenticated/student-attendance'
      path: '/student-attendance'
      fullPath: '/student-attendance'
      preLoaderRoute: typeof AuthenticatedStudentAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student-dashboard': {
      id: '/_authenticated/student-dashboard'
      path: '/student-dashboard'
      fullPath: '/student-dashboard'
      preLoaderRoute: typeof AuthenticatedStudentDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student-notices': {
      id: '/_authenticated/student-notices'
      path: '/student-notices'
      fullPath: '/student-notices'
      preLoaderRoute: typeof AuthenticatedStudentNoticesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teacher-attendance': {
      id: '/_authenticated/teacher-attendance'
      path: '/teacher-attendance'
      fullPath: '/teacher-attendance'
      preLoaderRoute: typeof AuthenticatedTeacherAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teacher-dashboard': {
      id: '/_authenticated/teacher-dashboard'
      path: '/teacher-dashboard'
      fullPath: '/teacher-dashboard'
      preLoaderRoute: typeof AuthenticatedTeacherDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teacher-notices': {
      id: '/_authenticated/teacher-notices'
      path: '/teacher-notices'
      fullPath: '/teacher-notices'
      preLoaderRoute: typeof AuthenticatedTeacherNoticesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teacher-subjects': {
      id: '/_authenticated/teacher-subjects'
      path: '/teacher-subjects'
      fullPath: '/teacher-subjects'
      preLoaderRoute: typeof AuthenticatedTeacherSubjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedStudentAttendanceRoute: typeof AuthenticatedStudentAttendanceRoute
  AuthenticatedStudentDashboardRoute: typeof AuthenticatedStudentDashboardRoute
  AuthenticatedStudentNoticesRoute: typeof AuthenticatedStudentNoticesRoute
  AuthenticatedTeacherAttendanceRoute: typeof AuthenticatedTeacherAttendanceRoute
  AuthenticatedTeacherDashboardRoute: typeof AuthenticatedTeacherDashboardRoute
  AuthenticatedTeacherNoticesRoute: typeof AuthenticatedTeacherNoticesRoute
  AuthenticatedTeacherSubjectsRoute: typeof AuthenticatedTeacherSubjectsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedStudentAttendanceRoute: AuthenticatedStudentAttendanceRoute,
  AuthenticatedStudentDashboardRoute: AuthenticatedStudentDashboardRoute,
  AuthenticatedStudentNoticesRoute: AuthenticatedStudentNoticesRoute,
  AuthenticatedTeacherAttendanceRoute: AuthenticatedTeacherAttendanceRoute,
  AuthenticatedTeacherDashboardRoute: AuthenticatedTeacherDashboardRoute,
  AuthenticatedTeacherNoticesRoute: AuthenticatedTeacherNoticesRoute,
  AuthenticatedTeacherSubjectsRoute: AuthenticatedTeacherSubjectsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
